### ISSUE TITLE
linking organisms to analysis

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#29] opened 2019-03-04 16:39 UTC
### executive summary
- populate the analysis_organism mview
- enable tripal_manage_analyses
- Run the gist which will populate organism_analysis based on the External Links field.

```
git clone https://gist.github.com/ec7078b8514a422e65db5e8d6cd29858.git
drush scr ec7078b8514a422e65db5e8d6cd29858/gistfile1.php
rm -rf ec7078b8514a422e65db5e8d6cd29858
```
### issue description

One of the early t3 migration goals will be to link organisms to analysis.  The [tripal manage analysis module provides this functionality](https://github.com/statonlab/tripal_manage_analyses). It also automatically migrates entries in the analysis_organism mivew into the new organism_analysis linker table.

As of right now, we only have 15/83 organisms linked (each to two analyses).  This mview was last populated in 2014 though.

```
select AO.analysis_id, O.organism_id, O.genus, O.species from chado.analysis_organism AS AO INNER JOIN chado.organism AS O ON O.organism_id = AO.organism_id ;
analysis_id	organism_id	genus	species
45	44	Orussus	abietinus
54	44	Orussus	abietinus
39	49	Athalia	rosae
30	49	Athalia	rosae
47	39	Ephemera	danica
27	39	Ephemera	danica
24	23	Cimex	lectularius
37	23	Cimex	lectularius
29	45	Ladona	fulva
50	45	Ladona	fulva
49	53	Frankliniella	occidentalis
44	53	Frankliniella	occidentalis
51	28	Leptinotarsa	decemlineata
34	28	Leptinotarsa	decemlineata
25	29	Parasteatoda	tepidariorum
56	29	Parasteatoda	tepidariorum
40	40	Ceratitis	capitata
28	40	Ceratitis	capitata
53	41	Oncopeltus	fasciatus
52	41	Oncopeltus	fasciatus
43	31	Eurytemora	affinis
48	31	Eurytemora	affinis
23	21	Anoplophora	glabripennis
38	21	Anoplophora	glabripennis
33	54	Diaphorina	citri
32	54	Diaphorina	citri
26	35	Pachypsylla	venusta
55	35	Pachypsylla	venusta
58	43	Trichogramma	pretiosum
57	43	Trichogramma	pretiosum
```

updating the mview gives me this:

```
select AO.analysis_id, O.organism_id, O.genus, O.species from chado.analysis_organism AS AO INNER JOIN chado.organism AS O ON O.organism_id = AO.organism_id ;
analysis_id	organism_id	genus	species
45	44	Orussus	abietinus
62	57	Drosophila	bipectinata
66	59	Drosophila	eugracilis
68	60	Drosophila	ficusphila
70	61	Drosophila	kikkawai
30	49	Athalia	rosae
27	39	Ephemera	danica
116	23	Cimex	lectularius
24	23	Cimex	lectularius
72	62	Drosophila	rhopaloa
74	63	Drosophila	takahashii
29	45	Ladona	fulva
64	58	Drosophila	elegans
44	53	Frankliniella	occidentalis
34	28	Leptinotarsa	decemlineata
93	66	Tigriopus	californicus
25	29	Parasteatoda	tepidariorum
53	41	Oncopeltus	fasciatus
117	41	Oncopeltus	fasciatus
43	31	Eurytemora	affinis
38	21	Anoplophora	glabripennis
115	21	Anoplophora	glabripennis
23	21	Anoplophora	glabripennis
60	56	Drosophila	biarmipes
26	35	Pachypsylla	venusta
58	43	Trichogramma	pretiosum
164	93	Apis	mellifera
163	93	Apis	mellifera
(28 rows)
```
so not much better unfortunately.  We'll need to investigate the organisms without analyses and ask if they have corresponding analyses, if they are present (for example in the links field) and understand why they cant be linked via the features

**Comment by bradfordcondon** [comment] 2019-03-04 17:09
```sql
select * from chado.feature f inner join chado.organism o ON o.organism_id = f.organism_id  where o.genus = 'Medauroidea';
feature_id	dbxref_id	organism_id	name	uniquename	residues	seqlen	md5checksum	type_id	is_analysis	is_obsolete	timeaccessioned	timelastmodified	searchable_name	organism_id	abbreviation	genus	species	common_name	comment
(0 rows)
```

So we definitely have organisms without features loaded--- unfortunately thats the only way to link prior to my `organism_analysis` table.

However, they are linked via teh `Links` fields: https://i5k.nal.usda.gov/medauroidea-extradentata . 

One possibility is we can fetch the nid when its "Annotation" or "Assembly" Methods.  We can then look up the analysis_id and link.

**Comment by bradfordcondon** [comment] 2019-03-04 17:52
I've written a gist that accomplishes this:

https://gist.github.com/bradfordcondon/ec7078b8514a422e65db5e8d6cd29858

prior to running

* have tripal_manage_analyses enabled
* ensure that all analyses that should be migrated will `strotlower` match `annotation` or `assembly`
* figure out if any of the other Links need to be migrated as well . (right now, that is biosample.)

**Comment by bradfordcondon** [comment] 2019-03-04 18:05
lingering issue:  

records listed under "Annotations" don't have corresponding nids:  `Error, no analysis found for that nid with URL annotations/739378`

**Comment by bradfordcondon** [comment] 2019-03-04 18:47
```php
  if (!$analysis_record_id) {

 $annotation_node = node_load($analysis_record_id);
      $data = $annotation_node->analysis;
      $annotation_analysis = chado_expand_var($data, 'field', 'analysis.description');
    dpm($annotation_node);

```

`$annotation_node` is always null?

**Comment by bradfordcondon** [comment] 2019-03-07 15:28
biosample link should be exported into a flat list for future eutils import.

**Comment by bradfordcondon** [comment] 2019-03-11 16:00
```
git clone https://gist.github.com/ec7078b8514a422e65db5e8d6cd29858.git
drush ec7078b8514a422e65db5e8d6cd29858/gistfile1.php
rm -rf ec7078b8514a422e65db5e8d6cd29858
```

**Comment by mpoelchau** [comment] 2019-03-15 16:31
This shows up in the output messages. Might need to go back to it to make sure it's not an issue. 
```
NOTICE (ORGANISM_MIGRATION): Bioproject link found: https://www.hgsc.bcm.edu/content/i5k-western-black-widow-spider
[site http://default] [TRIPAL NOTICE] [ORGANISM_MIGRATION] Bioproject link found: https://www.hgsc.bcm.edu/content/i5k-western-black-widow-spider
```

**Comment by mpoelchau** [comment] 2019-03-15 16:32
Looks like it's because we have the wrong link for the bioproject. I'll fix it on our prod and stage sites.

**Comment by bradfordcondon** [comment] 2019-03-15 16:38
i wrote that in as a requested.  Its not a bug.

>biosample link should be exported into a flat list for future eutils import.


It's to give you a record of the linked bioprojects.  Note that the links themselves **migrated to the new entities**.

**Comment by mpoelchau** [comment] 2019-03-15 16:44
No worries, I know it's not a bug. (It's a spider, har har). It wasn't a bioproject link, so it turns out it was a problem with our content. I fixed it, should be okay once I try this procedure on the next content dump.

**Comment by mpoelchau** [comment] 2020-09-30 16:08
Looks like this worked in the latest migration; closing.

**Closed by mpoelchau** 2020-09-30 16:08 UTC
Labels: ready-to-deploy, tripal 3 migration
