### ISSUE TITLE
Re-upload organism images 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#33] opened 2019-03-07 19:00 UTC
Images will not make it through the migration. Will need to re-associate the images with the organism page once we are done migrating from prod to the new tripal3 site.

**Comment by mpoelchau** [comment] 2019-08-16 18:19
When I try uploading an image on our Tripal3 site (clicked the 'Upload' button by 'Organism Image'), I get the below error (split into 2 screenshots since I couldn't get it all into 1):

<img width="445" alt="Screen Shot 2019-08-16 at 12 16 47" src="https://user-images.githubusercontent.com/5487172/63188879-e7622980-c01f-11e9-9fd0-12e3d9a478b2.png">
<img width="439" alt="Screen Shot 2019-08-16 at 12 16 52" src="https://user-images.githubusercontent.com/5487172/63188883-e9c48380-c01f-11e9-8139-78760c4ed0de.png">

@Ferrisx4 do you get the same error on your migrated copy of our site?

**Comment by Ferrisx4** [comment] 2019-08-16 18:31
When I try to add a new organism (with an image), after completing the form and hitting Submit, the site just complains vaguely about an error.

Trying to attach an image to an existing organism results in 
`Could not save the TripalEntity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ...', '56227', 'bio_data_1', '0', 'und', '417', '', '', '', '') ^`

I also noticed in both cases that after clicking the "Upload" button for the image, the webserver returned a 500 error for the thumbnail image: 
14:24:51 500 23 	GET /sites/default/files/styles/thumbnail/public/screen_shot_2019-08-16_at_12.08.15_pm_1.png?itok=Iv6Uwtpm HTTP/1.1

I am not sure if it is related, but during the T2-T3 conversion, one of the steps gave a number of warnings that the `sites/default/files/tripal_organism` directory needed to exist (I believe this is where Tripal attempts to store image files, among other things. I manually created this directory but the above issues still occur, and this might belong as its own Issue

**Comment by mpoelchau** [comment] 2019-08-16 19:46
We also have the sites/default/files/tripal_organism directory on our site.

**Comment by mpoelchau** [comment] 2019-08-16 19:52
Now just noticed that it uploaded the image into sites/default/files. However, the image still doesn't display on the page even after clearing the cache/hitting the reload button.

**Comment by mpoelchau** [comment] 2019-08-16 19:54
Thinking about this a bit more, I suspect it's a field configuration thing.

**Comment by Ferrisx4** [comment] 2019-08-16 19:59
Yes, I'm not convinced that all the errors I got above are directly caused by trying to attach an image but deeper issues involving discrepancies between the form data and how it is stored

**Comment by Ferrisx4** [comment] 2020-03-24 13:42
Images are now imported correctly via a script in the [post-migration stage](https://github.com/NAL-i5K/T2-to-T3-Upgrade-Guide/blob/29a7f9b49ec7aed6aabdb775409229423fad9af8/scripts/migrate_images.php)

The first comment I made in this thread was probably due to a VM/environment issue, not with the site itself.

Closing for now as the other issues in this thread are handled by the above script

**Closed by Ferrisx4** 2020-03-24 13:42 UTC
Labels: tripal 3 migration
